language: go
go: 
 - 1.5
before_install:
 - go get -t -v
 - go get -t -v ./cmd/hero
 - go get github.com/golang/lint/golint
before_script:
 - psql -c 'create database hero_test;' -U postgres
script:
 - make
